### ISSUE TITLE
Cannot 'manage' package version when branch name used in package version creation

### ISSUE THREAD

**Issue by simon-nowak** [ImJohnMDaniel/sfdx-toolbox-package-utils#4] opened 2022-03-18 15:10 UTC
Hello,

We recently updated our CI to take into account the branch name to build package version. In short
`sfdx force:package:version:create  [...] --branch $CI_COMMIT_REF_SLUG`

This is working as expected. The command `sfdx force:package:version:list` is showing us this output:
![image](https://user-images.githubusercontent.com/35262768/159026667-71012a17-4d86-4b23-ace3-932618329701.png)

However in other packages, when I run the command `sfdx toolbox:package:dependencies:manage` I have this result for **fflib-apex-mocks**
![image](https://user-images.githubusercontent.com/35262768/159028346-8d3c3300-3c9d-4c9f-bf73-12f0db5a14cf.png)

if I try `sfdx toolbox:package:dependencies:manage -b main` the output is similar
![image](https://user-images.githubusercontent.com/35262768/159028501-f18870be-7a58-466e-b8f1-c5ae18831fee.png)

So the plugin is only showing me the package version without branch. Before without indicating branch name, we were able to select package version here.

Are we doing something wrong?

Thank you

**Comment by ImJohnMDaniel** [comment] 2022-03-18 15:29
@simon-nowak, thanks for raising this issue.

Can you tell me what version of the CLI you are running and what version of the`@dx-cli-toolbox/sfdx-toolbox-package-utils` plugin you are running please?

**Comment by simon-nowak** [comment] 2022-03-18 15:41
sfdx-cli/7.137.1 darwin-x64 node-v14.15.5
@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.0

**Comment by ImJohnMDaniel** [comment] 2022-03-18 15:45
@simon-nowak, what happens when you run the manage command without specifying the branch flag?? 
```
    sfdx toolbox:package:version:manage
```
Do you then see the versions that were specified on the branch of "main"??

**Comment by ImJohnMDaniel** [comment] 2022-03-21 12:38
G'day @simon-nowak.  Thanks for sending over the extra info.  At this point, I have been able to reproduce the issue.  I am now working to figure out the root cause.  I will be in touch when I have something.

**Closed** 2022-03-27 19:24 UTC
Labels: investigating
